#[[subscriptions]]
#name = "机场 clash"
#default = "机场 ss 默认出口 不存在则选择第一个"
#url = "http://机场clash.ip.org/订阅链接内容为clash配置"

[[subscriptions]]
name = "机场 ss base64 编码"
# ss://2022-blake3-aes-128-gcm:aaa:zzz@proxy.ip.org:#节点名称
content = "c3M6Ly9NakF5TWkxaWJHRnJaVE10WVdWekxURXlPQzFuWTIwNldWZEdhRHBsYm5BMj09QHByb3h5LmlwLm9yZzojJUU4JThBJTgyJUU3JTgyJUI5JUU1JTkwJThEJUU3JUE3JUIw"

[[subscriptions]]
name = "机场 sing-box 配置"
url = '{"outbounds":[{"type":"shadowsocks","tag":"节点","server":"proxy.ip.org","server_port":123,"password":"密码"}]}'

[sing-box]
default = "机场 clash"
output = "config.json"
template = "config.template"
clash_port = 1234

# rule_set
[[sing-box.rule_set]]
tag = "geosite-谷歌配置通过国内中转下载"
url = "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo-lite/geosite/google.srs"
download_detour = "out-direct"

[[sing-box.rule_set]]
tag = "geosite-谷歌配置直连下载"
url = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo-lite/geosite/google.srs"
download_detour = "out-proxy"

# dns_rules
[[sing-box.dns_rules]]
server = "dns-direct"
domain_suffix = ["baidu.com"]

[[sing-box.dns_rules]]
server = "dns-proxy"
domain_suffix = ["google.com"]

# route_rules
[[sing-box.route_rules]]
outbound = "out-direct"
domain_suffix = ["baidu.com"]

[[sing-box.route_rules]]
server = "out-proxy"
domain_suffix = ["google.com"]

# block
[sing-box.block_rule]
rule_set = ["anti-ad"]

# direct
[sing-box.direct_rule]
domain = ["apple.com"]
domain_suffix = ["icloud.com"]
ip_cidr = ["127.0.0.1"]

# proxy
[sing-box.proxy_rule]
domain_suffix = ["google.com"]
rule_set = ["geosite-google"]
