version: 2

project_name: bemfa

builds:
  - id: bemfa
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -buildid=
    env:
      - CGO_ENABLED=0
    targets:
      - linux_arm64
      - windows_amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: bemfa
    ids:
      - bemfa
    formats: 
      - tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
      {{- if and .Amd64 (ne .Amd64 "v1") }}{{ .Amd64 }}{{ end -}}
    wrap_in_directory: true

upx:
  - enabled: true
    compress: best
