#!/bin/sh

[ -f "/etc/.upgrade" ] && exit 0

cat <<EOF >"/etc/config/nginx"

config main global
    option uci_enable "true"

config server "_lan"
    list listen "80 default_server"
    list listen "[::]:80 default_server"
    option server_name '_lan'
    list include "conf.d/*.locations"
    option access_log "off; # logd openwrt"

config server "_redirect2ssl"
    option server_name '_redirect2ssl'
    option access_log "off; # logd openwrt"

EOF

cat <<'EOF' >"/etc/nginx/uci.conf.template"
# Consider using UCI or creating files in /etc/nginx/conf.d/ for configuration.
# Parsing UCI configuration is skipped if uci set nginx.global.uci_enable=false
# For details see: https://openwrt.org/docs/guide-user/services/webserver/nginx
# UCI_CONF_VERSION=1.2

worker_processes auto;

user root;

include module.d/*.module;

events {}

http {
    access_log off;
    log_format openwrt
        '$request_method $scheme://$host$request_uri => $status'
        ' (${body_bytes_sent}B in ${request_time}s) <- $http_referer';

    include mime.types;
    default_type application/octet-stream;
    sendfile on;

    server_names_hash_bucket_size 64;

    client_max_body_size 3072M;
    client_body_buffer_size 128K;
    large_client_header_buffers 4 512k;

    gzip on;
    gzip_vary on;
    gzip_proxied any;

    root /www;

    #UCI_HTTP_CONFIG
    include conf.d/*.conf;
}

EOF

exit 0
