name: Build sing-box

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: "1.14.0"
      ref:
        type: string
        default: "testing"

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          repository: "SagerNet/sing-box"
          ref: "${{ inputs.ref }}"

      - uses: actions/checkout@main
        with:
          path: build_repo
          sparse-checkout: sing-box

      - uses: actions/setup-go@main

      - run: |
          git tag ${{ inputs.version }} -f

          cp build_repo/sing-box/.goreleaser.yaml . \
            && cp -a build_repo/sing-box/patch/. . \
            && rm -rf build_repo
          go mod tidy

      - uses: goreleaser/goreleaser-action@master
        with:
          args: release --snapshot --clean

      - uses: dev-drprasad/delete-older-releases@v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: sing-box

      - uses: softprops/action-gh-release@v2
        with:
          name: sing-box
          tag_name: sing-box
          files: dist/*.{tar.gz,zip}
