name: Build sing-box

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        type: string
      ref:
        description: "ref"
        type: string

jobs:
  calc_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calc_version.outputs.version }}
      ref: ${{ steps.calc_version.outputs.ref }}

    steps:
      - id: calc_version
        run: |-
          release_url="https://api.github.com/repos/SagerNet/sing-box/releases/latest"
          version=${{ inputs.version }}
          ref=${{ inputs.ref }}

          echo "input version='$version'"
          echo "input ref='$ref'"

          if [ -z "$ref" ]; then
            ref=$(curl -sSL "$release_url" | jq -r ".tag_name")
            if [ -z "$version" ]; then
              version="$ref"
            fi
          fi

          if [ -z "$version" ]; then
            version=$(curl -s "$release_url" | jq -r ".tag_name")
          fi

          echo "output version='$version'"
          echo "output ref='$ref'"

          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "ref=$ref" >> "$GITHUB_OUTPUT"

  main:
    runs-on: ubuntu-latest
    needs:
      - calc_version

    steps:
      - uses: actions/checkout@main
        with:
          repository: "SagerNet/sing-box"
          ref: "${{ needs.calc_version.outputs.ref }}"

      - uses: actions/checkout@main
        with:
          path: build_repo
          sparse-checkout: sing-box

      - uses: actions/setup-go@main

      - uses: actions/cache@main
        id: cache-win7
        with:
          key: go_win7_1253
          path: ~/go/go_win7

      - if: steps.cache-win7.outputs.cache-hit != 'true'
        run: .github/setup_go_for_windows7.sh

      - uses: actions/cache@main
        id: cache-ghr
        with:
          key: ghr
          path: ~/go/bin/ghr

      - if: steps.cache-ghr.outputs.cache-hit != 'true'
        run: |
          cd $HOME
          git clone --depth=1 https://github.com/nekohasekai/ghr ghr
          cd ghr
          go install -v .

      - run: |
          echo "HOME=$HOME" >> "$GITHUB_ENV"
          git tag ${{ needs.calc_version.outputs.version }} -f

          cp build_repo/sing-box/.goreleaser.yaml . \
            && cp -a build_repo/sing-box/patch/. . \
            && rm -rf build_repo
          go mod tidy

      - uses: goreleaser/goreleaser-action@master
        env:
          GOPATH: ${{ env.HOME }}/go
        with:
          args: release --snapshot --clean

      - run: mkdir -p release && mv dist/*.{tar.gz,zip} release

      - uses: dev-drprasad/delete-older-releases@v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: sing-box

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          export PATH="$PATH:$HOME/go/bin"
          IFS='/' read -r user repo <<< "$GITHUB_REPOSITORY"
          VERSION=""
          if [ "${{ needs.calc_version.outputs.version }}" == "${{ needs.calc_version.outputs.ref }}" ]; then
            VERSION="${{ needs.calc_version.outputs.version }}"
          else
            VERSION="${{ needs.calc_version.outputs.version }}-${{ needs.calc_version.outputs.ref }}"
          fi
          ghr -u $user -r $repo --replace "sing-box-$VERSION" release
